name: PR Validator
on:
  pull_request:
    branches:
    - master
    - pr_validator_regex 
    types: [opened, edited, synchronize]
jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: "Validate SUMMARY"
        uses: CleverRaven/pr-validator@master
        with:
          description-regex: '(?:<!--[\s\S\n]*?-->)|SUMMARY: +(None|((Features|Content|Interface|Mods|Balance|Bugfixes|Performance|Infrastructure|Build|I18N) +".*"))'
          description-regex-flags: 'igm'
